In [18]:
import numpy as np
from numpy import linalg  # linearalgebra

In [19]:
# Matrix 
# A.dot_prod(Ainv) = I

In [25]:
a = np.array([[2,3],[1,2]])
print(a)
print(a.shape)

[[2 3]
 [1 2]]
(2, 2)


In [28]:
a_inv = linalg.inv(a)
print(a_inv)

[[ 2. -3.]
 [-1.  2.]]


In [29]:
res = np.dot(a,a_inv)
print(res)

[[1. 0.]
 [0. 1.]]


#### Matrix Inverse
1) If A is a sqaure matrix,then there exists a matrix B such that np.dot(A,B) = I where I is the identity matrix

#### Trace
1) Sum of primary diagonal elements


In [30]:
h = np.array([[1,2,10],[4,5,6],[7,8,9]])
trace = np.trace(h)
print(h)
print(trace)

[[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]
15


#### Eigen Values and Eigen Vectors
Link -> https://www.mathsisfun.com/algebra/eigenvalue.html

#### Eigen values and Eigen Vectors

<b>Av = λv</b>

where <br>
A = is the square matrix<br>
λ = Eigen value<br>
v = Eigen vectors

Original matrix A can be obtained from λ and v as follows
np.dot(np.dot(v,λ),inv(v))

Primary Diagnoal = Diagonal matrix elements starting from top left to bottom right.


In [36]:
a = np.array([[2,3],[1,2]])
print(a)
print(a.shape)

[[2 3]
 [1 2]]
(2, 2)


In [41]:
eig_val,eig_vec = linalg.eig(a)
print(eig_val)
print(eig_vec)
inv_eig_vec = linalg.inv(eig_vec) 
print(inv_eig_vec)

[3.73205081 0.26794919]
[[ 0.8660254 -0.8660254]
 [ 0.5        0.5      ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]


In [42]:
print(a)

[[2 3]
 [1 2]]


In [47]:
eval1 = np.array([[3.73205081,0],[0, 0.26794919]])
print(eval1)
r1 = np.dot(eig_vec,eval1)
print(r1)
r2 = np.dot(r1,linalg.inv(eig_vec))
print(r2)

[[3.73205081 0.        ]
 [0.         0.26794919]]
[[ 3.23205081 -0.23205081]
 [ 1.86602541  0.1339746 ]]
[[2. 3.]
 [1. 2.]]


In [33]:
eval1 = np.array([[3.73205081,0],[0, 0.26794919]])
print(eval1)
r1 = np.matmul(eig_vec,eval1)
print(r1)
inv_eig_vect = linalg.inv(eig_vec)
print(inv_eig_vect)
r2 = np.matmul(r1,inv_eig_vect)
print(r2)

[[3.73205081 0.        ]
 [0.         0.26794919]]
[[ 3.23205081 -0.23205081]
 [ 1.86602541  0.1339746 ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]
[[2. 3.]
 [1. 2.]]


In [32]:
res = (eig_vec@eval1)@linalg.inv(eig_vec)
print(res)

[[2. 3.]
 [1. 2.]]


#### Eigen value and Eigen Vector using Scipy

In [48]:
from scipy.linalg import eig as eigen

In [36]:
eig_val,eig_vec = eigen(a)
print(eig_val)
print(eig_vec)
inv_eig_vec = linalg.inv(eig_vec) 
print(inv_eig_vec)

[3.73205081+0.j 0.26794919+0.j]
[[ 0.8660254 -0.8660254]
 [ 0.5        0.5      ]]
[[ 0.57735027  1.        ]
 [-0.57735027  1.        ]]
